#!/sbin/sh
setprop service.adb.root 1
if [ -e /sbin/bootrec-device ]
then
  /sbin/bootrec-device
fi

# let's force adb mode on startup, because AOSP/CM10 are stupid and disable it by default
echo 0 > /sys/class/android_usb/android0/enable
echo 0fce > /sys/class/android_usb/android0/idVendor 
echo 614f > /sys/class/android_usb/android0/idProduct
echo "mass_storage,adb" > /sys/class/android_usb/android0/functions
echo 1 > /sys/class/android_usb/android0/enable
stop adbd

if [ -s /dev/keycheck ]
then
  mount -o remount,rw rootfs /
  umount -l /system
  umount -l /data
  umount -l /mnt/sdcard
  umount -l /sdcard
  rm -r /sdcard
  rm -r /mnt/sdcard
  mkdir /sdcard
  mkdir /tmp
  rm /etc
  mkdir /etc
  #umount -l /cache
  mount /dev/block/mmcblk0p1 /sdcard
  chmod 755 /res/aromapreinstall/aroma-installer
  chmod 755 /res/aromapreinstall/*.sh
  /res/aromapreinstall/aroma-installer 1 0 "/res/aromapreinstall/aroma-installer-res.zip"
  #touch /tmp/bootrec
fi

if [ -e /cache/recovery/boot -o -e /tmp/bootrec ]
then
  rm /cache/recovery/boot
  rm /tmp/bootrec
  umount -l /cache
  mount /dev/block/mmcblk0p1 /sdcard
  /sbin/recovery&/sbin/adbd
fi

#multiboot stuff
mount /dev/block/mmcblk0p1 /sdcard
if   [ -e /cache/defaultboot_2 -o -e /cache/multiboot2 ]
then
  umount /system
  umount /data
  mount -t ext2   -o rw,loop                       /sdcard/system2.ext2.img    /system
  mount -t ext2   -o ro,loop,remount               /sdcard/system2.ext2.img    /system
  mount -t ext2   -o rw,loop,noatime,nosuid,nodev  /sdcard/userdata2.ext2.img  /data
  rm /cache/multiboot2
elif [ -e /cache/defaultboot_3 -o -e /cache/multiboot3 ]
then
  umount /system
  umount /data
  mount -t ext2   -o rw,loop                       /sdcard/system3.ext2.img    /system
  mount -t ext2   -o ro,loop,remount               /sdcard/system3.ext2.img    /system
  mount -t ext2   -o rw,loop,noatime,nosuid,nodev  /sdcard/userdata3.ext2.img  /data
  rm /cache/multiboot3
else
  mount -t yaffs2 -o rw                            /dev/block/mtdblock0        /system
  mount -t yaffs2 -o ro,remount                    /dev/block/mtdblock0        /system
  mount -t yaffs2 -o rw,noatime,nosuid,nodev       /dev/block/mtdblock1        /data
fi

# multiboot fixes
chown system:system /data
chmod 0771 /data
mkdir /data/dontpanic 
    chown root:log /data/dontpanic 
    chmod 0750 /data/dontpanic 
    copy /proc/apanic_console /data/dontpanic/apanic_console
    chown root:log /data/dontpanic/apanic_console
    chmod 0640 /data/dontpanic/apanic_console
    copy /proc/apanic_threads /data/dontpanic/apanic_threads
    chown root:log /data/dontpanic/apanic_threads
    chmod 0640 /data/dontpanic/apanic_threads
mkdir /data/misc
    chown system:misc /data/misc
    chmod 0771 /data/misc
mkdir /data/misc/bluetoothd
    chown bluetooth:bluetooth /data/misc/bluetoothd
    chmod 0770 /data/misc/bluetoothd
mkdir /data/misc/bluetooth
    #chown system:system /data/misc/bluetooth
    chown bluetooth:bluetooth /data/misc/bluetooth
    chmod 0770 /data/misc/bluetooth
mkdir /data/misc/keystore
    chown keystore:keystore /data/misc/keystore
    chmod 0700 /data/misc/keystore
mkdir /data/misc/keychain
    chown system:system /data/misc/keychain
    chmod 0771 /data/misc/keychain
mkdir /data/misc/vpn
    chown system:vpn /data/misc/vpn
    chmod 0770 /data/misc/vpn
mkdir /data/misc/systemkeys
    chown system:system /data/misc/systemkeys
    chmod 0700 /data/misc/systemkeys
mkdir /data/misc/wifi
    chown wifi:wifi /data/misc/wifi
    chmod 0770 /data/misc/wifi
mkdir /data/local
    chown root:root /data/local
    chmod 0751 /data/local
mkdir /data/misc/wifi/sockets
    chown wifi:wifi /data/misc/wifi/sockets
    chmod 0770 /data/misc/wifi/sockets
chmod 0660 /data/misc/wifi/wpa_supplicant.conf
chown wifi.wifi /data/misc/wifi/wpa_supplicant.conf
symlink /data/misc/wifi/wlan0 /data/system/wpa_supplicant
mkdir /data/misc/dhcp
    chown dhcp:dhcp /data/misc/dhcp
    chmod 0770 /data/misc/dhcp
mkdir /data/local/tmp
    chown shell:shell /data/local/tmp
    chmod 0771 /data/local/tmp
mkdir /data/data
    chown system:system /data/data
    chmod 0771 /data/data
mkdir /data/app-private
    chown system:system /data/app-private
    chmod 0771 /data/app-private
mkdir /data/app-asec
    chown root:root /data/app-asec
    chmod 0700 /data/app-asec
mkdir /data/app
    chown system:system /data/app
    chmod 0771 /data/app
mkdir /data/property
    chown root:root /data/property
    chmod 0700 /data/property
mkdir /data/ssh
    chown root:shell /data/ssh
    chmod 0750 /data/ssh
mkdir /data/ssh/empty
    chown root:root /data/ssh/empty
    chmod 0700 /data/ssh/empty
mkdir /data/radio
    chown radio:radio /data/radio
    chmod 0770 /data/radio
mkdir /data/radio/log
    chown radio:radio /data/radio/log
    chmod 0770 /data/radio/log
mkdir /data/resource-cache
    chown system:system /data/resource-cache
    chmod 0771 /data/resource-cache
mkdir /data/lost+found
    chown root:root /data/lost+found 
    chmod 0770 /data/lost+found 
mkdir /data/drm
    chown drm:drm /data/drm
    chmod 0770 /data/drm

    
# Couldn't be bothered doing this in init syntax (I'm ignorant) so we'll link dalvik here instead
mkdir /data/dalvik-cache
    chown system:system /data/dalvik-cache
    chmod 0771 /data/dalvik-cache
ln -s /data/dalvik-cache /cache/dalvik-cache
    chown system:system /cache/dalvik-cache
    chmod 0771 /cache/dalvik-cache

#continue booting


