#!/sbin/sh

# fixing CPU clocks to avoid issues in recovery
echo 1024000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 122000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

echo 0 > /sys/class/android_usb/android0/enable
echo 0FCE > /sys/class/android_usb/android0/idVendor
echo 615D > /sys/class/android_usb/android0/idProduct
echo mass_storage,adb > /sys/class/android_usb/android0/functions
echo 1 > /sys/class/android_usb/android0/enable
stop adbd

# trigger blue LED
echo '255' > /sys/class/leds/blue/brightness
# trigger short vibration
echo "200" > /sys/class/timed_output/vibrator/enable
# back key
cat /dev/input/event1 > /dev/keycheck&
sleep 3
# LED off
echo '0' > /sys/class/leds/blue/brightness

kill -9 $!
