#!/sbin/sh

# fixing CPU clocks to avoid issues in recovery
echo 1017000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 249600 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
# correct LCD-backlight brightness
echo '255' > /sys/class/leds/lcd-backlight/brightness


mount /data
mount /system

rm /cache/update.prop
rm /cache/recovery/enterpreinstall
rm /cache/recovery/enterrecovery

if [ -e /data/libroparsertest.so -o -e /system/etc/dop.iso ]
then
    touch /cache/recovery/enterrecovery
    touch /cache/recovery/enterpreinstall
elif [ -e /cache/recovery/boot ]
then
    rm /cache/recovery/boot
    touch /cache/recovery/enterrecovery
elif [ ! -e /system/build.prop ]
then
    touch /cache/recovery/enterrecovery    
elif [ ! -e /cache/recovery/extendedcommand ]
then
    mount /data
    mount /system
    mount /dev/block/mmcblk0p1 /sdcard
    /sbin/sh /res/aromapreinstall/checkupdate.sh

    if [ -e /cache/update.prop ]
    then
        # USB fixup "mass_storage, adb"
        TAG="usb"
        VENDOR_ID=0FCE
        PID_PREFIX=6
        USB_FUNCTION=mass_storage,adb
        # hardcoded PID for PLAY
        PID=615D
        echo 0 > /sys/class/android_usb/android0/enable
        echo ${VENDOR_ID} > /sys/class/android_usb/android0/idVendor
        echo ${PID} > /sys/class/android_usb/android0/idProduct
        /system/bin/log -t ${TAG} -p i "usb product id: ${PID}"
        echo ${USB_FUNCTION} > /sys/class/android_usb/android0/functions
        /system/bin/log -t ${TAG} -p i "enabled usb functions: ${USB_FUNCTION}"
        echo 1 > /sys/class/android_usb/android0/enable
        /system/bin/setprop sys.usb.state ${USB_CONFIG_PROP}
        
        mount /dev/block/mmcblk0p1 /sdcard

        mount /data
        mount /system
        mkdir /tmp
        
        chmod 755 /res/aromapreinstall/aroma-installer
        chmod 755 /res/aromapreinstall/*.sh
        /sbin/adbd_rec &
        /res/aromapreinstall/aroma-installer 1 0 "/res/aromapreinstall/aroma-installer-res.zip"
        rm /cache/update.prop
    fi
    umount -l /sdcard
    # trigger blue LED
    echo '255' > /sys/class/leds/blue/brightness
    # trigger short vibration
    echo "200" > /sys/class/timed_output/vibrator/enable
    # back key
    cat /dev/input/event1 > /dev/keycheck&
    sleep 3
    # LED off
    echo '0' > /sys/class/leds/blue/brightness
    kill -9 $!
fi

if [ -s /dev/keycheck -o -e /cache/recovery/enterrecovery -o -e /cache/recovery/extendedcommand ]
then
    rm /cache/recovery/enterrecovery

    mount -o remount,rw rootfs /

    # USB fixup "mass_storage, adb"
    TAG="usb"
    VENDOR_ID=0FCE
    PID_PREFIX=6
    USB_FUNCTION=mass_storage,adb
    # hardcoded PID for PLAY
    PID=615D
    echo 0 > /sys/class/android_usb/android0/enable
    echo ${VENDOR_ID} > /sys/class/android_usb/android0/idVendor
    echo ${PID} > /sys/class/android_usb/android0/idProduct
    /system/bin/log -t ${TAG} -p i "usb product id: ${PID}"
    echo ${USB_FUNCTION} > /sys/class/android_usb/android0/functions
    /system/bin/log -t ${TAG} -p i "enabled usb functions: ${USB_FUNCTION}"
    echo 1 > /sys/class/android_usb/android0/enable
    /system/bin/setprop sys.usb.state ${USB_CONFIG_PROP}

    # shifting to "umount -l /partition" to avoid mounting issues in recovery
    umount -l /system
    umount -l /data
    umount -l /sdcard
    umount -l /mnt/sdcard
    rm -r /sdcard
    rm -r /not/sdcard
    mkdir /sdcard
    mkdir /tmp
    rm /etc
    mkdir /etc
    
    cp /recovery.fstab /etc/recovery.fstab
    mount /dev/block/mmcblk0p1 /sdcard

    mount /data
    mount /system
    /sbin/sh /res/aromapreinstall/checkupdate.sh

    if [ -e /cache/recovery/enterpreinstall -o -e /cache/update.prop ] && [ ! -e /cache/recovery/extendedcommand ]
    then
        chmod 755 /res/aromapreinstall/aroma-installer
        chmod 755 /res/aromapreinstall/*.sh
        if [ ! -e /cache/update.prop ]
        then
            echo "type=fresh" >> /cache/update.prop
        fi
        /sbin/adbd_rec &
        /res/aromapreinstall/aroma-installer 1 0 "/res/aromapreinstall/aroma-installer-res.zip"
        rm /cache/update.prop
    fi

    umount -l /system
    umount -l /data
    umount -l /cache
    /sbin/recovery &
    /sbin/adbd_rec recovery 
fi

#continue booting

